### ISSUE TITLE
Error message Open Olat

### ISSUE THREAD

**Issue by MGA1108** [OpenOLAT/OpenOLAT#106]
We use the Academy solution from Open Olat as an on-prem solution. Unfortunately, we have recently received the following error message when users try to open their courses (see attachment).
How can we fix this error or, better still, can you fix this error for us?
[Screenshot Open Olat.pdf](https://github.com/user-attachments/files/17277520/Screenshot.Open.Olat.pdf)

**Comment by gnaegi** [comment]
Hi

Lookup the error in the logfile using the error number. The error number itself does not reveal the problem, it is just the reference to the relevant log entry.

If you need any help setting up or running your system, please ask for commercial help. GitHub is more for code related discussions.
