### ISSUE TITLE
Solution does not unfold on iPhone

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#11]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

On iPhone Browsers the folded solution does not unfold if you click/push on the link. It seems to be an IOS specific issue. The unfolding works on a small viewport on a desktop Firefox.

### What I did:

1. Create a QTI 2.1 Test with a single choice question (Test Option "Show solutions" is ON)
2. Do and finish the test
3. Push on "Solution"

### What I expect to happen:

Solution is folded out.

### What actually happened:

Nothing

![oo_solution](https://user-images.githubusercontent.com/339384/48133835-5a23c480-e298-11e8-86c0-285890d1e4f0.png)

### What version of OpenOlat I am using:

OpenOlat 13.0.0b8 (master)
IOS 12.0.1
Safari / Firefox / Opera Mini (all the same behavior)

**Comment by lainsr** [comment]
You can follow the issue here: https://jira.openolat.org/browse/OO-3727

**Comment by tomgross** [comment]
:tada: That was quick. I can confirm it works. Thank you so much!
