### ISSUE TITLE
Usability issue: Too much validation on preview form

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#12]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

In preview mode test elements are validated unnecessarily. If you try the element you have to "save" it first in order to continue.

### What I did:

1. Create a QTI 2.1 Test with a single choice question 
2. Go to "Preview" tab
3. Click one option.
4. Click another tab.

### What I expect to happen:

Tab is switched immediately.

### What actually happened:

Form validation is triggered and a warning appears.
![oo_form_preview](https://user-images.githubusercontent.com/339384/48134311-e1be0300-e299-11e8-9cd7-e30ca2b31f19.png)

### What version of OpenOlat I am using:

OpenOlat 13.0.0b8 (master)

**Comment by lainsr** [comment]
As you don't save your question, it's the wanted behaviour.

**Comment by tomgross** [comment]
But why is the button "Save answer" here if you don't **_save_**? This is confusing for the user.

**Comment by lainsr** [comment]
To test the feedbacks for example, or use the "Output data" tool to see the variables used and processed by QTI 2.1 engine if you work with questions imported from an other editor or written per hand in XML.

**Comment by gnaegi** [comment]
It is a preview of how it looks when taking the item in a real test. It is an exact rendering of how it will look like.

**Comment by tomgross** [comment]
@lainsr @gnaegi Thanks for the clarification. Maybe a note above the preview would do the trick.
![oo_form_preview_note](https://user-images.githubusercontent.com/339384/48152160-68d3a100-e2c3-11e8-9198-03c47cb8daa5.png)

```html
<div class="alert alert-info" role="alert">This is a realistic version of the Single Choice element with all validations in place except it does not <em>save</em> any data. </div>
```

**Comment by gnaegi** [comment]
No changes planned
