### ISSUE TITLE
Remove Google+

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#14]
Since Google+ is closing down it probably should be removed from OpenOlat.

See https://www.blog.google/technology/safety-security/project-strobe/

**Comment by gnaegi** [comment]
Users currently using it depend on it, we can not just remove it. They first have to migrate to another solution. As long as google+ is still alive I don't see a reason why it should be removed from the code. We will remove it when google+ authentication is not working anymore. 

If you don't want to have it in your installation you can simply disable it in the admin site.

**Comment by tomgross** [comment]
@gnaegi Thanks for the answer. I'm not suggesting this is super urgent. A friendly proactive reminder to the people who are using Google+ that they need to look for an alternative until August 2019 is most likely enough for now.

I guess it is better to give the people you are referring to a chance to plan the switch than to turn off the feature on short notice or have the feature broken in autumn 2019.

**Comment by lainsr** [comment]
OO-3860 The Google+ login provider is transformed in a Google Sign-In provider via OAuth 2.0. It's mostly an upgrade of the code and some cosmetic changes (the icon loses is + and wording)
