### ISSUE TITLE
Usability Issue: Usage of "Save" button is inconsistent

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#15]
## BUG/PROBLEM REPORT (OR OTHER COMMON ISSUE)

The usage of the "Save" button (in administration forms?) is inconsistent. While some option pages have it other lack it.

### What I did:

1. Go to Adminstration -> Login -> SMS  (no "Save" button)
2. Go to Administration -> Login -> Self registration ("Save" button)

### What I expect to happen:

The "Save" button is consistently there or not. (I prefer if it is not there and the user is informed that the changes have been saved by a short visible popup which goes away by itself.)

### What actually happened:

Some option pages need to be explicitly saved with a "Save" button while others are save transparently (without a notice).

With "Save" button
![oo_save_button](https://user-images.githubusercontent.com/339384/48138954-a5909f80-e2a5-11e8-99df-215b66d4a6c8.png)

Without "Save" button
![oo_no_save_button](https://user-images.githubusercontent.com/339384/48138981-b4775200-e2a5-11e8-982b-2399ebdc4719.png)

### What version of OpenOlat I am using:

OpenOlat 13.0.0b8 (master)

**Comment by gnaegi** [comment]
Checkbox changes are simple to have without a button - they can always represent the saved state, a button is not necessary. 

However, in input fields / textareas etc. it is unclear if the value visible in the browser has been persisted or not. Thus, we show a button, render the button orange to indicate that an explicit form submit is necessary.

**Comment by tomgross** [comment]
Thanks @gnaegi . It sounds reasonable to omit the submit button, if it is not (logically) necessary. Still as a user I except some kind of unified feedback, if a persistent change was made to the application. See https://www.smashingmagazine.com/2017/06/designing-efficient-web-forms/#visual-feedback

**Comment by tomgross** [comment]
I'm closing this due lack of activity.
