### ISSUE TITLE
REST API call to get access configuration

### ISSUE THREAD

**Issue by step4** [OpenOLAT/OpenOLAT#18]
Hey there,

with Olat v12.5 as an author it is possible to create course elements via REST API, e.g. with 
`/repo/courses/{courseId}/elements/singlepage`
and afterwards you can publish the changes with 
`/repo/courses/{courseId}/publish?locale&access&membersOnly`

My Question is if you can get the access code, the one you send with the publich call, via a GET call?
So before I publish a course again, I want to ask for the access configuration which is set before.

**Comment by lainsr** [comment]
Hi

In 12.5 you cannot do that. There is a method in 13.x but 13.x works slightly differently and doesn't used the access code but a status with additional flags (for all users / guests access).

**Comment by step4** [comment]
Ok thank you for that information.

**Comment by step4** [comment]
One little question more:
Can you point me to the new API or which were changed?

**Comment by uhensler** [comment]
The documentation of the actual API  (OpenOLAT 13.2.1 as of today) is available here: https://learn.olat.com/restapi/api/doc

**Comment by step4** [comment]
So I had a look at the new docs and a lot of the new source code, but I could not find a way to ask for the current state of the status, accessAllUsers and accessGuests like in 
https://github.com/OpenOLAT/OpenOLAT/blob/9d8605c16b2e36857ec370dacb33467188434c52/src/main/java/org/olat/restapi/repository/course/CourseWebService.java#L214-L255

Is it true, that you only can set those values but not get them?

**Comment by uhensler** [comment]
A `Course` is a special kind of a `RepositorEntry`. So you get the status in the `RepositoryEntryWebService`.
https://github.com/OpenOLAT/OpenOLAT/blob/9d8605c16b2e36857ec370dacb33467188434c52/src/main/java/org/olat/restapi/repository/RepositoryEntryWebService.java#L796-L805

**Comment by lainsr** [comment]
In 13.x you can use the following URL if you have the repository entry key:

GET repo/entries/{repositoryEntryKey}/access

There is currently no equivalent in the course API. I try to add for 13.2.2 (OO-3963)

**Comment by step4** [comment]
Nice Thank you, it works!
