### ISSUE TITLE
how to download extra large file ?

### ISSUE THREAD

**Issue by 171563857** [OpenOLAT/OpenOLAT#2]
i try export a 5GB file about course content, but the download speed was dropped to 0 kb/s when i was downloading 1GB

**Comment by 171563857** [comment]
@gnaegi @lainsr @uhensler @aschne 
: )

**Comment by gnaegi** [comment]
There is no limit on OpenOLAT side, you probably have some settings in Apache or Tomcat that prevent you from downloading more. Or your tmp filesystem does not have enough space...
