### ISSUE TITLE
how to develop based on openolat???

### ISSUE THREAD

**Issue by yuanbaojian** [OpenOLAT/OpenOLAT#20]
hi there.  
    I am a company employee. Recently, we are currently researching openolat. We don't know much about the architecture, and there are very few documents about openolat. I would like to ask, do you have relevant technical documentation about openolat, it will be kind  if you send it to my gmail.  Here is my email address.   Anywany ,thank you a lot!!!!!
312ybj@gmail.com

**Comment by lainsr** [comment]
Hi

No, we don't have a lot of technical documentations. You can find some informations on the mailing list: https://groups.google.com/forum/#!forum/openolat
For a quick overview of the UI: https://groups.google.com/d/msg/openolat/H2LhTb-Rna4/7vuvtLNEAwAJ
