### ISSUE TITLE
openolat  integration with oracle

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#22]
I have created all the tables in the setupdatabase.sql file. in our case auto db updrade is not possible since db is maintain by seperate team we cannot exceute ddl  statements  with our user.. 
what all "alter*." sql files we need to run for proper working of openolat application. configutation wise i have done all the changes.
Please help me on this

**Comment by uhensler** [comment]
The setupdatabase.sql contains the whole sql schema. So you do not need to run any alter statement.

When you update OpenOlat from a previous version, you have to run the statements found in src/main/resources/database/oracle.
