### ISSUE TITLE
Open olat Video tutorials

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#23]
Do we have any video tutorials available in any of the sites.
Installation wise i have completed every thing
 it would be helpful for us to easily setup application.
need helps on 
role management.
curriculam creation 
course creation

**Comment by uhensler** [comment]
We do not have video tutorials, but a written user manual: [https://confluence.openolat.org/display/OO140EN](url)

**Comment by tomgross** [comment]
There are some videos on SWITCHtube:

- https://tube.switch.ch/channels/ab0141ed
- https://tube.switch.ch/channels/049b8055

Some of them are dated and some cover very special topics but might serve you as a starting point.
