### ISSUE TITLE
Is there any way to restrict  ldap job to pull user data from particular group

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#24]
i dont want to pull all ldap user data from ldap end point . Is there any way to limit job to pull data from particular group.

Do we can set the config in olat.properties file how?

**Comment by lainsr** [comment]
Yes, you can add a filter in your olat.local.properties. The property is ldap.ldapUserFilter.

Here is an example that we use currently:
ldap.ldapUserFilter=(&(objectClass=${ldap.ldapUserObjectClass})(memberOf=CN=OpenOlat,OU=FRENTIX,DC=frentix,DC=local))

**Comment by rageshpillai** [comment]
Ok thanks
