### ISSUE TITLE
Storing data in common storage

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#29]
we are planning to deploying the application in 2 machines for the fail over purpose.
can we store the userdata.dir path to to common path. I got some issues when we are deploying the application with 2 different user directory path.

Or is there any other way to store the data in aws

**Comment by lainsr** [comment]
You cannot store the data on aws. But you can have a common path for the 2 machines. OpenOlat writes the data in the database AND on the file system. In your case OpenOlat can only run on one machine at a given time, not both.

**Comment by rageshpillai** [comment]
Is there is any issue when running  olat in 2 machine with common path.
for handling fail over we have to deploy it in atleast 2 machine
Kindly suggest a solution for this

**Comment by lainsr** [comment]
Yes, using OpenOlat in a cluster mode is theoretically possible but complicated as many internal components need to be clustered like the JMS server, caches... In our experience, it's not worse the price. OpenOlat on one machine is on our servers more stable and more reliable than a cluster setup.
The second point is that user session are not serialised. If one of your machine crashed, the users who work on this machine cannot continue on the second machine, they need to login again and the current state of the session is lost.
Essentially we only restart OpenOlat for updates.
