### ISSUE TITLE
Unable to upload profile image from profile 

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#31]
i can able to upload  profile images manage user settings page but not not able upload from the profile link . Image upload option is disabled for the user.

**Comment by lainsr** [comment]
Do you want to disable upload of profile images for your users? Or you cannot upload one as a standard user?

**Comment by rageshpillai** [comment]
Is there any functionality to restrict photo upload

**Comment by lainsr** [comment]
Yes, but it's a feature which only come with 14.1 and 14.1 is still in development. In 14.1 you can set in olat.local.properties the following property to true:
user.portrait.managed=true
