### ISSUE TITLE
restrict displaying port name in external url

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#32]
We have deployed the application and  have a domain name for the application.
But for some pages port number is appended to the domain name for that external links and the links are not accessible due to the port name
how to remove port number  from the domain name

for the external links displaying as below
https://domainname :port no
we have disables server port option in the property file then after the application is not running
Pls help me on this

**Comment by lainsr** [comment]
We cannot disable the port options in flat.local.properties, they are needed. You can set them to accommodate the standard ports of Tomcat (port 8080) like this:

server.port=8080
server.port.ssl=0

Or if you have setup https (with Tomcat or Apache):

server.port=0
server.port.ssl=443
