### ISSUE TITLE
User session is not managing properly

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#33]
After successful login when clicking on the browser back button it's getting redirect to login page. How to restrict this. Even if a valid session exist it should not redirect to login page.

**Comment by gnaegi** [comment]
Why is this wrong? 

History 0: Login page
History 1: Page after login page
Back to history 0 => Login page

This is what I expect when clicking back after login. When visiting the login page the session is always invalidated so you can log in with another user or start all over. This is the standard behaviour in OpenOlat and there is no config to change this.

**Comment by rageshpillai** [comment]
This is not the right way. Even if the session is exist it should not go to the login page. It should redirect to the same page until unless we are logging out. This is the normal behaviour in all sites . Pls do it needfull

**Comment by gnaegi** [comment]
This depends on your viewpoint. An LMS that is used in public education and is beeing used in public internet terminals such as a library it is very well desired that when opening the login screen a session that might have been not correctly closed (e.g. by just closing the browser window) is invalidated. Sure, there are other scenarios where an other behaviour might fit better. 

We can implement another session behaviour for you if you want. If you are interested, please contact me privately and I will send you a quote for this development request. Of course you are always free to modify the code yourself.
