### ISSUE TITLE
Coaching tab not showing any user 

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#35]
When clicking on th coaching section in the navigation panel it's not showing any user. I have enabled coach in the administration. I am using postgres as my db. And also one more issue is in some pages back breadcrumb link is not working.
![IMG_20190827_110515](https://user-images.githubusercontent.com/5021230/63743857-30856980-c8bb-11e9-9871-da36b9e4cbfd.jpg)

**Comment by gnaegi** [comment]
Sorry, GitHub is not a place to ask user questions, this is the developer area to discuss software bugs. Please read the manual how to use OpenOlat. You can ask user related questions on the google mailing list. 

To see something in the coaching tool you need to be coach of some users. Make sure you are coach in a course and you have participants in those courses.

**Comment by rageshpillai** [comment]
That is ok. But why that back button is not working in the breadcrumb i tested in 3 browsers  it's not working any way

**Comment by lainsr** [comment]
Back button must be implemented. I doesn't come "naturally". If you have an issue with it, please say exactly where. What do you mean by back button in breadcrumb? The "<" symbol?
