### ISSUE TITLE
java.lang.ClassNotFoundException: org.olat.restapi.security.RestApiSessionListener

### ISSUE THREAD

**Issue by uboa3774** [OpenOLAT/OpenOLAT#37]
**Env:**
Device: Windows10
Tomcat: v8.0
JDK: 1.8.0_221

**What I did:**
1. Follow the guide finish set-up step1.2.3.
2. ClassNotFoundException.
3. Clean the project & tomcat(I also have tired mvn clean)
4. Re-build this project.
5. ClassNotFoundException, and I can't see any file in target/classes

**What I expect to happen:**
Fix the ClassNotFoundException.

**What version of OpenOlat I am using:**
OpenOlat master

**Comment by uboa3774** [comment]
I fixed this problem by link src/test/java/olat.local.properties to olat.local.properties

**Comment by gnaegi** [comment]
I'm glad you could fix your configuration problem. Please note that we do not officially support Windows as as plattform. If you against all recommendations want to use Windows, make sure that you run all jUnit and Selenium testcases and fix all the occurring issues.
