### ISSUE TITLE
Enabling Cross Origin Resource Sharing

### ISSUE THREAD

**Issue by gitaumoses4** [OpenOLAT/OpenOLAT#38]
I followed this issue https://jira.openolat.org/plugins/servlet/mobile#issue/OO-615 and added `allow.cross.origin.doman` in `olat.local.properties`, to no success.

**Comment by uhensler** [comment]
This option was removed in https://jira.openolat.org/browse/OO-3352.

**Comment by gitaumoses4** [comment]
Hi @uhensler , Kindly let me know how I can get access to the JIRA board. I currently can't see the stories.

**Comment by gnaegi** [comment]
@gitaumoses4 this issue is visible only for members of the OpenOlat partnership program since it has a security level rating. All security ratet issues are not publicly visible.

**Comment by gitaumoses4** [comment]
Thank you for the clarification @gnaegi.
I still don't have any guidelines on how I can enable CORS on my REST API. Where can I get documentation on how to do so?
Kindly.

**Comment by gnaegi** [comment]
The cross origin filter is not there anymore. It was a relict when we thought about implementing a new UI using the REST API. We then dropped this idea and focused on a responsive layout instead. The REST API is not meant to support an alternative app, it is more for remote management (sync with other course management system or to automate some tasks). 

Right now, it you need the cross origin filter you need to implement it yourself. Digg in the repository for the old CrossOriginFilter to get some hints.

**Comment by gitaumoses4** [comment]
That is very much helpful.
I really appreciate it. Thanks so much @gnaegi
