### ISSUE TITLE
Using "Back" button in Browser doesn't work

### ISSUE THREAD

**Issue by argh87** [OpenOLAT/OpenOLAT#39]
It simply doesn't work. Navigating via browser is impossible and makes it a pain to use.

**Comment by gnaegi** [comment]
Can you please describe in detail where the back button does not work. OpenOlat is an application and not a website, the behaviour of back in workflows and forms is not always clear. It must be implemented for each scenario. It works in most cases, but we might have missed some. To fix them we need to understand where you are and where you have been before and where you expect to land when you go "back".

**Comment by lainsr** [comment]
If the "Back" doesn't work at all, check your configuration in olat.local.properties. The following properties must be configured and match your actual URL:

server.port.ssl
server.port
server.domainname

**Comment by lainsr** [comment]
No response
