### ISSUE TITLE
REST API endpoint for fetching course elements

### ISSUE THREAD

**Issue by gitaumoses4** [OpenOLAT/OpenOLAT#40]
Hi,
I created a structure course element on `repo/courses/:courseId/elements/structure`
But it seems there is no endpoint to get a list of elements for a course.

Am I missing something? Kindly help.

**Comment by lainsr** [comment]
Hi

No, there is no specific endpoint for a list. But you can download the XML file which describe the whole course with repo/courses/:courseId/elements/runstructure .

**Comment by gitaumoses4** [comment]
Wow...  
Thanks for the feedback. @lainsr
