### ISSUE TITLE
testImportICal_outlookFullDay test fails if environment timezine is not CEST

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#5]
Running OpenOlat tests on environments with timezones other than CEST will cause 

https://github.com/OpenOLAT/OpenOLAT/blob/master/src/test/java/org/olat/commons/calendar/manager/ICalFileCalendarManagerTest.java#L650 test to fail.

See 
- https://circleci.com/gh/tomgross/OpenOLAT/23 (no TZ - defaults to UTZ) vs.
- https://circleci.com/gh/tomgross/OpenOLAT/40 (TZ set to `Europe/Zurich`)

**Comment by lainsr** [comment]
Test will be ignore if the time zone is not the right one.
