### ISSUE TITLE
OAuth2 for services like OneDrive, Google Drive etc.

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#52]
I have seen OpenOlat does support OAuth2 for user authentication (https://www.openolat.com/features/releasenotes/new-features-10-0/?lang=en). Is there a way to authenticate services (like OneDrive, Google Drive, Dropbox, etc.) with OAuth2?
My usecase is to include a cloud storage as a learning resource. Is there any documentation how to achive this?

**Comment by gnaegi** [comment]
Hi Tom
No, currently oAuth is only supported for login. OneDirve, GoogleDrive, Dropbox etc all have different API's, there is noting implemented so far.
