### ISSUE TITLE
How can we change the certificate text in pdf 

### ISSUE THREAD

**Issue by rageshpillai** [OpenOLAT/OpenOLAT#53]
I just want to change the text for the certificate. How can we change that. Is there any way to change the certificate templates.

**Comment by rageshpillai** [comment]
Where the default certificate template is saved?

**Comment by lainsr** [comment]
The default template is in code: https://github.com/OpenOLAT/OpenOLAT/blob/master/src/main/resources/org/olat/course/certificate/template.pdf

You can edit a PDF editor like Acrobat Reader Pro

You can upload new certificates in Administration > e-Assessment > Certificates -> the tab for templates or in the course settings.
