### ISSUE TITLE
Javascript files not loadable

### ISSUE THREAD

**Issue by BlackRose01** [OpenOLAT/OpenOLAT#62]
Hello,

currently I try to install OpenOlat on my Raspberry Pi and basically it works but when I visit the webinterface I got every time the messages that my browsers (firefox, opera) cannot load the required javascript files. The error messages are 404 but the browser says that the files cannot load because the HTTP Header option "X-Content-Type-Options" is wrong (value: nosciff). Even when I disable this Option the errors are still there.

My installed version is 14.2.8.

Hope for help.

Best Regards,
BlackRose01

Opera error description:
![js_error](https://user-images.githubusercontent.com/7542316/80318971-2337ca80-880e-11ea-939e-c8d88e2d6dcd.PNG)

Firefox error description:
![firefox_error](https://user-images.githubusercontent.com/7542316/80319046-8de90600-880e-11ea-9ae2-867bf81c7764.PNG)

**Comment by lainsr** [comment]
Hi

I think you have set the option

olat.debug=true

This option is only for development within an IDE.

Best regards
Stéphane

**Comment by BlackRose01** [comment]
Hi,

thanks for your help. That was the problem.

Best regards,
BlackRose01
