### ISSUE TITLE
Unknown CSS properties

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#65]
There are some more occurences of unknown CSS properties. These are:

 - `footnote-style-position` @ https://github.com/OpenOLAT/OpenOLAT/blob/master/src/main/java/org/olat/core/logging/activity/doc-files/specification.html#L336
- `webkit-font-smoothing` supposed to be `-webkit-font-smoothing` (see http://maxvoltar.com/archive/-webkit-font-smoothing) @ https://github.com/OpenOLAT/OpenOLAT/blob/master/src/main/webapp/static/themes/light/modules/_cal.scss#L213
- `white-sprace` most likely `white-space` @ https://github.com/OpenOLAT/OpenOLAT/blob/master/src/main/webapp/static/themes/light/modules/_evaluation_form.scss#L443

What should we do with these?

**Comment by lainsr** [comment]
I fix the properties in master
