### ISSUE TITLE
Uploading video in podcast course module fails

### ISSUE THREAD

**Issue by tomgross** [OpenOLAT/OpenOLAT#68]
Trying to upload a video in the podcast course module always results in an error:

_Learning resource could not be added. Either its format or its version is not supported by OpenOlat._

<img width="873" alt="Screenshot 2020-06-06 at 08 08 33" src="https://user-images.githubusercontent.com/339384/83937472-2ccd2e80-a7cd-11ea-8c97-f9c147e34742.png">

Versions I'm using:
OpenOlat 14.1.7 & OpenOlat master
PostgreSQL 11.7
AdoptOpenJDK - build 1.8.0_242-b08

Here is a selenium Test illustrating the issue: https://github.com/tomgross/OpenOLAT/pull/17/commits/12d48a3c32fbac0205b673ef9d2fb2d356fe3aaf

**Comment by tomgross** [comment]
Here is one of the example videos I used: https://pixabay.com/videos/download/video-33256_tiny.mp4?attachment

**Comment by gnaegi** [comment]
Why are your uploading a video in the dialog to upload a podcast? Uploading videos works perfectly in the places where videos are expected. There is no magic conversion of a video file to a podcast resource. The dialog is missleading, but there is nothing wrong here.

**Comment by tomgross** [comment]
Thanks for your feedback @gnaegi Is it safe to assume that the import buttons on the "Create" / "Change" option can be removed to avoid confusing the user? 

<img width="899" alt="Screenshot 2020-06-06 at 19 24 06" src="https://user-images.githubusercontent.com/339384/83950532-b7447b00-a82b-11ea-9f22-8edefd8c7237.png">

This is also the only way, which is documented in the OpenOlat handbook at https://confluence.openolat.org/display/OO150DE/Podcast+erstellen

**Comment by lainsr** [comment]
These buttons are useful. A podcast in OpenOlat is a learn resource that you can export and import from an instance of OpenOlat to an other one. The import button is important to upload a learn resource of type podcast. With the import URL button, you can create a learn resource of type podcast from the URL of a podcast flux and bind it to the course element in one step.
