### ISSUE TITLE
> Why do you open a pull-request and close it right away? Please don't play with our repo, you can play with your own. Thank you.

### ISSUE THREAD

**Issue by gnaegi** [OpenOLAT/OpenOLAT#71]
> I accidentially created this pull request. Sorry for any inconvenience. Mistakes happen.

ok. Just because Tom from your organization did the same several weeks ago, I thought it is becoming a pattern.

**Comment by tomgross** [comment]
Sorry from my side to. If you have a fork of a github repo and do a PR within your repo githup proposes the original repo as base for the PR. This easily leads to this unwanted behavior.
Unfortuantely github does currently not offer an easy way to change the default PR base for forks.
See: https://stackoverflow.com/questions/31573448/how-to-set-default-fork-for-pull-requests
