### ISSUE TITLE
Feature request: Upload corrections for all students at once

### ISSUE THREAD

**Issue by ssiccha** [OpenOLAT/OpenOLAT#75]
Dear Dev team,

I can download submissions of all students for a task at once by clicking on the task and then clicking "Alle abgegebenen Dokumente herunterladen" ("download all submitted documents"). 

I would like to be able to somehow upload the corrections for all students at once. Off the top of my head I'd suggest the following. When I download the submissions into a folder `submission`, I see that, for a students `student` for whom I already uploaded corrections, OpenOLAT creates subfolders `submission/student_folder/3_corrections/`. I could for example create those subfolders myself, put the corrections in there, and then upload a zip archive of `submission`.

When I need to upload corrections for, 40 students say, for every single one I have to click through a few dialogues, each time waiting for the next dialogue to load, and at the end wait for the corrections to finish uploading. That easily takes half an hour or longer each week during the teaching term.

**Comment by gnaegi** [comment]
Bulk assessment is available in the assessment tool, see here: 

https://confluence.openolat.org/display/OO153EN/...+create+a+bulk+assessment+for+submission+tasks

**Comment by ssiccha** [comment]
Thanks for the link. I already found that but unless I'm reading the page wrong, there is no option to also add attachments right?

What we do is, we add annotations to the submissions of the students. What would be great is a way to bulk upload the annotated files back into Olat.

**Comment by gnaegi** [comment]
_Only for bulk assessment of the task module:
Create a folder for each individual student who receives a return file. Enter the individual feedback for each person there. Zip the file and upload it in the first step under "Assessment values"._

It is somewhere in the fineprint ;-)

**Comment by ssiccha** [comment]
Ah, awesome! Thanks a lot. :D
