### ISSUE TITLE
Bug: bulk assessment does not work with individual feedback files

### ISSUE THREAD

**Issue by ssiccha** [OpenOLAT/OpenOLAT#76]
Dear OpenOLAT devs,

We use OpenOLAT 15.3.3 in german, so the names I use for the buttons might be a bit off. I made a bulk assessment as per [this website](https://confluence.openolat.org/pages/viewpage.action?pageId=88768647). After it didn't work the first time, to reproduce my problem I created a new task, had a student upload a dummy submission, started a bulk assessment, entered a table with 0 points and uploaded a zip file with a feedback file for the respective student. After that I clicked "immediately perform assessment".

Assigning points works fine. The feedback files were recognized, namely the `# files` column shows `1` for the respective students. Also during the step "Check Data / Daten überprüfen" it says "Check successful / Überprüfung erfolgreich". See the screenshot below. 
![massenbewertung-kaputt](https://user-images.githubusercontent.com/11617763/100109203-e39c9400-2e6b-11eb-8e3c-ae2ed41bb1cb.png)

However, when checking the students task pages the feedback files do not appear. Neither myself nor the students can access them. I might have done something wrong, but then I'd expect an error message.
![korrektur-nicht-vorhanden](https://user-images.githubusercontent.com/11617763/100110111-e21f9b80-2e6c-11eb-9f3e-f07cc6eb887f.png)

Update: I just double-checked the first task where I tested the bulk assessment several times. There a test file I used for the bulk-assessment appeared. Could it be that the file only appears with a delay?
![korrektur-vorhanden](https://user-images.githubusercontent.com/11617763/100111728-af76a280-2e6e-11eb-9569-8953329b9e67.png)

**Comment by ssiccha** [comment]
I think I've figured it out!

Let's say I have two users `user1` and `user2`. I create a folder `corrections/` with two subfolders `user1/` and `user2/`. Then I put feedback files into the respective folders. Now if I create a zip file which contains folders `user1/` and `user2/`, then uploading them via the bulk assessment works fine, i.e. the feedback files are also added to the student pages.

If however I create a zip file which contains the folder `corrections/` with subfolders `user1/` and `user2/`, then bulk assessment correctly assigns the feedback files to the students, that is as in the first screenshot above we have `# Dateien` > 0, but afterwards the files _are not shown on the student pages_ as in the second screenshot above.

**Comment by uhensler** [comment]
Even the files are listed in the wizard, files in subfolders are not taken into account when processing the files (see [OO-5172](https://jira.openolat.org/browse/OO-5172)).

As a workaround, you can zip the users' folders directly instead of the parent folder.

<img width="433" alt="compress" src="https://user-images.githubusercontent.com/3603541/102988341-1477f380-4514-11eb-8431-4012f3f83c32.png">
