### ISSUE TITLE
Error in starting

### ISSUE THREAD

**Issue by zhengyakai** [OpenOLAT/OpenOLAT#77]
dear developers:
   I downloaded this project today and configured it according to the regulations, but an error was reported after startup:
   "Security framework of XStream not explicitly initialized, using predefined black list on your own risk."
   and  when i  visit  http://localhost:8080/olat , it was 404 error.
   could u help me what should I do?

**Comment by gnaegi** [comment]
You can ignore the XStream error, you don't have to worry about this, this is a configuration issue we have with OpenOlat, but it is just a warning. 

The 404 is not related to the XStream problem. You have something wrong. Check your logfiles (catalina.out, olat.log etc)
