### ISSUE TITLE
How to map a user to any existing organization?

### ISSUE THREAD

**Issue by amoghshylendra** [OpenOLAT/OpenOLAT#79]
I don't see any option for the admin to map users to organizations. Once the user is created, it is getting created under default organization - OpenOLAT. I need to create users under various organizations, of different types. Could you please help here?

**Comment by gnaegi** [comment]
Please do not use GitHub Issues to ask user questions. Issues are bus etc, not questions. Please use the public mailing list https://groups.google.com/g/openolat for this kind of help. 

Regarding your question: 
- When creating a user you can choose the organization
- Once created you can add or change the organization relation in the user profile in the "roles" tab
