### ISSUE TITLE
Clicking Log Out doesn't log you out

### ISSUE THREAD

**Issue by p-h** [OpenOLAT/OpenOLAT#8]
This is happening on olat.zhaw.ch

Steps to reproduce:

- Log in
- Click Log out
- Click log in again

And you are back in. This could be a security issue if used on a publicly accessed computer.

**Comment by gnaegi** [comment]
Hi

This is not OpenOLAT related and not a bug per se. It is a "feature" of Shibboleth, the distributed Single-Sign-On  infrastructure used by SWTICH AAI to authenticate to many resources automatically. The authentication that is still valid is actually the Shibboleth session and not the OpenOLAT session. The Shibboleth session has a much longer lifetime than the OpenOLAT sesseion.

Close your browser and your Shibboleth session will also be closed. This information also appears when logging out from OpenOLAT. 

Cheers
Florian
