### ISSUE TITLE
Set environment instead of local

### ISSUE THREAD

**Issue by punit-porwal** [OpenOLAT/OpenOLAT#81]
Hi Team,

I have tried to set env. value from  ~/bin/setenv.sh is QA using below spring properties but seems it is still not pick olat.qa.properties file and still taking olat.local.properties file
-Dspring.profiles.active=qa
Could you please suggest any other way we have to set env as qa/prod/uat instead of only local

Let me know if you will require more input.

Thanks
Punit Porwal

**Comment by uhensler** [comment]
Hi Punit

olat.qa.properties does not work, because the file in not loaded by Spring.

The olat.local.properties has to be somewhere in the class path. To use different files for different environments you can put them in different directories and the copy the files in the classpath. Or use symlinks. Or play with the classpath itself.

Hope this helps.

**Comment by punit-porwal** [comment]
Thanks Uhensler for your review and sharing the information.
Actual I have tried as suggested approach but seems both are not working for me like
a) Create qa directory and moved olat.local.properties (with QA properties)
cd classes 
mkdir qa
cp olat.qa.properties qa/olat.local.properties 
Bounce the app to start picking new one under qa class folder
Getting olat.local.properties  not found

b) Tried with symlinks 
cd classes
ln -s olat.local.properties  qa/olat.local.properties 
Bounce the app to start picking new one under qa class folder
Getting olat.local.properties  not found

Anyway I add my QA DB & other setting into classes/olat.local.properties
and working expected
but in real scenario I have to change every time prod/qa properties into local and then have to deployed 
if require please check in future release you can fetch env value from Spring so it will be fixed.

Thanks for your help!

**Comment by lainsr** [comment]
Hi

We don't plan to load different olat.local.properties based in the spring profile. Our standard way to work is to drop the olat.local.properties in the lib/ of Tomcat with database drivers and log4j2 configuration. For test instance, we override the settings in the olat.local.properties with -Doption=somethin in bin/setenv.sh . You can override all properties in the olat.local.properties with -D arguments. For example:

-Dsmtp.host=disabled
