### ISSUE TITLE
does openolat support SAML Authentication 

### ISSUE THREAD

**Issue by punit-porwal** [OpenOLAT/OpenOLAT#83]
Hi Team, could you please confirm if Openolat can able to use SAML Authentication (Security Assertion Markup Language)
if yes, where and what kind of properties have to change.

**Comment by gnaegi** [comment]
Hi

You can use various variants of oAuth2 based authentication and also Shibboleth, which is based on SAML. However, SAML itself is not supported at this time out of the box.

Please us the mailing list for this kind of questions, GitHub is not meant for user questions. You can find the list here: 
[https://groups.google.com/g/openolat](https://groups.google.com/g/openolat)

 Regards
Florian

**Comment by punit-porwal** [comment]
Thanks Gnaegi for your input.
