### ISSUE TITLE
LDAP users sync user status 

### ISSUE THREAD

**Issue by sandrosousa** [OpenOLAT/OpenOLAT#84]
How to sincronize user status from LDAP to OpenOlat, which atributes we must match in configuration file?
LDAP user status atribute is "useraccountcontrol"

The goal is if a user is disable in LDAP it should have the status "Disable" in OpenOlat.

**Comment by gnaegi** [comment]
It is not possible to set the OpenOlat user status based on an LDAP attribute, it is not implemented. You can however automatically delete users in OpenOlat that do not exist in LDAP anymore. Be careful with this option. 

Please us the mailing list for this kind of questions, GitHub is not meant for user questions. You can find the list here:
https://groups.google.com/g/openolat

Regards
Florian
