### ISSUE TITLE
openolat_1612 war deployment - Application at context path [/openolat_1612] could not be started

### ISSUE THREAD

**Issue by shakthimaan** [OpenOLAT/OpenOLAT#87]
I am trying to deploy the latest `openolat_1612.war` file using the Apache Tomcat GUI on Parabola GNU/Linux-libre (Arch linux variant), and I am getting the following error:

![openolat-deployment-could-not-be-started](https://user-images.githubusercontent.com/312622/149994092-41a15cf9-ec5b-4c19-9dbf-ad12ee3294f5.png)

Using the following software versions:
* Apache Tomcat/10.0.15-1
* OpenJDK 17.0.1+12
* PostgreSQL 13.4.6

I had updated `/var/lib/tomcat10/webapps/manager/WEB-INF/web.xml` to allow 200 MB upload file size:
```
    <multipart-config>
      <max-file-size>209715200</max-file-size>
      <max-request-size>209715200</max-request-size>
      <file-size-threshold>0</file-size-threshold>
    </multipart-config>
  </servlet>
```
1. Please advise on how to resolve the same.
2. The following instructions, https://www.openolat.com/fileadmin/adminwiki/_START_.html, require to create a separate /home openolat user. I was able to install Tomcat, OpenJDK and PostgreSQL on the test system. If you can provide OpenOLAT instructions to deploy using the system-wide installation instead of /home/openolat, it will be helpful.

Thank you!

**Comment by gnaegi** [comment]
Hi 

Please also have a look at the first line of the install manual where it says: "Tomcat 9, Java 11 and PostgreSQL 12.". hope that helps fixing your problem. Postgres 13 should work fin, but the Java and Tomcat version you use are not recommended. 

Florian

**Comment by shakthimaan** [comment]
> "Tomcat 9, Java 11 and PostgreSQL 12."

Is there a specific *nix distribution that provides these specific versions?

**Comment by kaoliva** [comment]
Good morning

Most actual Linux distributions will have some version of PostgreSQL
11.x or higher. That should work.

Apache Tomcat can be downloaded here: https://tomcat.apache.org/

For Java, we can recommend AdoptOpenJDK
(https://adoptopenjdk.net/installation.html#x64_linux-jdk) but there are
many others out there.

Kind Regards
Oliver


Am 19.01.22 um 03:52 schrieb Shakthi Kannan:
