### ISSUE TITLE
Keycloak configuration in tomcat/lib/olat.local.properties is not used

### ISSUE THREAD

**Issue by wolfaba** [OpenOLAT/OpenOLAT#89]
Hello,
we try to configure Keycloak oAuth using `olat.local.properties` file. We copy and set some of the options from `openolat_1624/WEB-INF/classes/serviceconfig/olat.properties` to `tomcat/lib/olat.local.properties`

```
oauth.keycloak.enabled=true
oauth.keycloak.root=true
oauth.keycloak.client.id=OIDC-CLIENT-ID
oauth.keycloak.client.secret=OIDC-CLIENT-SECRET
oauth.keycloak.endpoint=https://OIDC-SERVER/
oauth.keycloak.realm=OIDC-REALM
```

After tomcat restart, there is still native OLAT login without cloud login.

If we insert the

```
oauth.default=true
```

option, then even native OLAT does not work, the login window show no username and passwort inputs and no login button. Only one white line (see the screenshot ![olat-no-login](https://user-images.githubusercontent.com/34514550/173364815-f0feef93-a7e6-480a-a030-772fe3a24017.png) ).

If we configure Keycloak in the admin webgui, it works perfect.

The configuration from webgui is probably saved in `olatdata/system/configuration/org.olat.login.oauth.OAuthLoginModule.properties`. We wanted to compare the configuration in `org.olat.login.oauth.OAuthLoginModule.properties` with our our configuration in `olat.local.properties` and verify if our manuall configuration is correct, but the file `org.olat.login.oauth.OAuthLoginModule.properties` is encrypted.

Could you please give us any hint, what is incorrect with our configuration in `olat.local.properties` file?

Does openolat read and process the file `olat.local.properties` correctly? Is maybe problem that the `olat.local.properties` configuration is not encrypted?

Thank you very much.

Regards,

Robert Wolf.

**Comment by gnaegi** [comment]
To configure keycloak it is best to use the web ui. As you said, it works then. If you really want to configure via olat.local.properties you must be sure that the file ``olatdata/system/configuration/org.olat.login.oauth.OAuthLoginModule.properties`` is empty. Whatever is in there wins over the olat.local.properties. 

If you don't want the OpenOlat provider to show up on the login screen, disable the login provider: 

```
olatprovider.enable=false
olatprovider.default=false
```

Cheers
Florian

**Comment by wolfaba** [comment]
Hello Florian,

thank you very much for your answer.

We would prefer to configure olat with plain text files using puppet, so using web UI would be unwanted manual step.

What exactly do you mean with "empty file"? Can the file be removed? Or must be the file present with size of 0 Bytes? Or should the file contain encrypted empty content? How can we create encrypted empty content? I have read the source code and found generateKey() function used in loadPropertiesFromFile() and savePropertiesAndFireChangedEvent() functions so I could probably decrypt and encrypt the file, but I am no java developer, so I don't know how make some simple console programm to encrypt and decrypt the file. Is it possible to make the same encryption/decryption using any linux command line tool, e.g. openssl?

If the file `olatdata/system/configuration/org.olat.login.oauth.OAuthLoginModule.properties` does not exist

```
root@olat:/srv/openolat [0]# ls -l olatdata/system/configuration/org.olat.login.oauth.OAuthLoginModule.properties 
ls: cannot access 'olatdata/system/configuration/org.olat.login.oauth.OAuthLoginModule.properties': No such file or directory
```

or is empty

```
root@olat1-1:/srv/openolat [2]# touch olatdata/system/configuration/org.olat.login.oauth.OAuthLoginModule.properties 
root@olat1-1:/srv/openolat [0]# ls -l olatdata/system/configuration/org.olat.login.oauth.OAuthLoginModule.properties 
-rw-r--r-- 1 root root 0 Jun 14 09:14 olatdata/system/configuration/org.olat.login.oauth.OAuthLoginModule.properties
```

openolat still ignores the keycloak configuration from `tomcat-9.0.63/lib/olat.local.properties` and shows native login only 
![olat-native-login-only](https://user-images.githubusercontent.com/34514550/173518851-9db9a068-5a13-499b-aa7d-7f74f41a7251.png)

I don't see any errors or warnings about keycloak or reading any properties in olat.log and catalina.out.

Do you have any other idea?

Thank you very much for your help.

Regards,

Robert Wolf.

**Comment by lainsr** [comment]
Hi

The configuration is ignored. I open an issue for it and fix will come with 16.2.5 release at friday:
https://jira.openolat.org/browse/OO-6266

Regards

**Comment by wolfaba** [comment]
Hello @lainsr ,
thank you very much for your confirmation. We will wait for 16.2.5.
Regards,
Robert Wolf

**Comment by wolfaba** [comment]
Hello,
version 16.2.5 installed and keycloak config from olat.local.properties works as expected.
Thank you :+1: 
Regards,
Robert Wolf.
