### ISSUE TITLE
LDAP config in olat.local.properties

### ISSUE THREAD

**Issue by wolfaba** [OpenOLAT/OpenOLAT#90]
Hello,

if we configure Keycloak Login in UI (and in new version 16.2.5 in olat.local.properties too I hope), then after Keycloak login we get error

![olat-keycloak-login-auth-not-successfull](https://user-images.githubusercontent.com/34514550/174054706-a0f054b5-6390-4084-986e-0831b70801b3.png)

So we want to configure LDAP to get all accounts from AD.

I have prepared LDAP configuration, first to test login and create account on login. See [olat-ldap-config.txt](https://github.com/OpenOLAT/OpenOLAT/files/8918222/olat-ldap-config.txt)

But if I try to login, I get following error in [olat.log](https://github.com/OpenOLAT/OpenOLAT/files/8918189/olat.log)

Do you have any idea, what's wrong in our configuration?

May I have additional question to LDAP config? What are these options and how to configure them correctly?

```
ldap.coachRoleAttribute=
ldap.coachRoleValue=

ldap.user.groupAttribute=
ldap.user.groupAttribute.values=
ldap.user.groupAttributeSeparator=

ldap.user.coachedGroupAttribute=
ldap.user.coachedGroupAttribute.values=
ldap.user.coachedGroupAttributeSeparator=
ldap.groupCoachAsParticipant=

ldap.authorsGroupBases=
ldap.authorRoleAttribute=
ldap.authorRoleValue=

ldap.userManagersGroupBases=
ldap.userManagerRoleAttribute=
ldap.userManagerRoleValue=

ldap.groupManagersGroupBases=
ldap.groupManagerRoleAttribute=
ldap.groupManagerRoleValue=

ldap.qpoolManagersGroupBases=
ldap.qpoolManagerRoleAttribute=
ldap.qpoolManagerRoleValue=

ldap.curriculumManagersGroupBases=
ldap.curriculumManagerRoleAttribute=
ldap.curriculumManagerRoleValue=

ldap.learningResourceManagersGroupBase=
ldap.learningResourceManagerRoleAttribute=
ldap.learningResourceManagerRoleValue=
```

Thank you very much for your answer and help.

Regards,

Robert Wolf.

**Comment by lainsr** [comment]
Hi

The OAuth Login doesn't create per default new account. It's often not desired. There is an option in Administration > Login > Cloud Login > Allow registration. This option is currently not available in olat.local.properties. I will add it in the next release.

Best regards

**Comment by wolfaba** [comment]
Hello @lainsr ,

> The OAuth Login doesn't create per default new account

yes, I understand this. So we wanted to sync AD accounts to OLAT using LDAP. Using LDAP we can limit users from AD, who can use to olat. In Keycloak, there are many other users which should not get access to olat, so "Allow registration" is unwanted.

But now back to LDAP. Do you have any idea, why the LDAP does not work? Or do you see any error in our configuration?

In the olat.log, there is the first error NPE:

```
Throwable occurred, logging the full stacktrace: java.lang.NullPointerException
  at java.naming/javax.naming.directory.BasicAttributes.get(BasicAttributes.java:164)
  at org.olat.ldap.manager.LDAPLoginManagerImpl.findAuthenticationByLdapAuthentication(LDAPLoginManagerImpl.java:924)
```

Do you have any idea why?

Thank you.

Regards,

Robert Wolf.

**Comment by wolfaba** [comment]
Hello,
I have tried to verify LDAP communication and there looks everything fine:

1. olat makes bind using the ldap.ldapSystemDN account with successful result
2. olat search the account entered in login form with successful result and one account found
3. olat makes bind with the found DN and entered password with successful result

And then comes the error 
![olat-ldap-error](https://user-images.githubusercontent.com/34514550/175068186-d90b0891-ec8a-44a0-b1ec-9fbbea0df78d.png)
 and there is NPE in the log 
[olat.log.txt](https://github.com/OpenOLAT/OpenOLAT/files/8959031/olat.log.txt)


Do you see the problem?

Thank you very much.

Regards.

Robert Wolf.

**Comment by wolfaba** [comment]
Hello,
as I have written, I am no developer, but I have tried to read the code now and please allow me one question: is the LDAP functionality fully implemented? Do you know, if someone already use the LDAP?
Maybe I have only incorrect configuration. I have found now following note:
```
# Attribute used as username to log in. Note: the configured login attribute MUST be one of the mapped attributes below, e.g. genericTextProperty1
# If the login attribute should not be visible in OO, then disable the OO user property in all contexts.
ldap.login.attribute=${ldap.attributename.useridentifyer}
```
We use `mail` as `useridentifyer` but I have not set the mapping. So I have tested to configure mapping now:
```
ldap.attributename.useridentifyer=mail
ldap.attributename.nickName=mail
ldap.login.attribute=mail
ldap.attrib.gen.map.ldapkey1=mail
ldap.attrib.gen.map.olatkey1=userID
```
Is this correct or not?

But the NPE still comes to log.
```
Throwable occurred, logging the full stacktrace: java.lang.NullPointerException
at java.naming/javax.naming.directory.BasicAttributes.get(BasicAttributes.java:164)
at org.olat.ldap.manager.LDAPLoginManagerImpl.findAuthenticationByLdapAuthentication(LDAPLoginManagerImpl.java:924)
```

So back to code:

Line 924 in `LDAPLoginManagerImpl.java`
```
String uid = getSingleAttributeValue(attrs.get(uidAttribute));
```

Line 906 in `LDAPLoginManagerImpl.java`
```
String uidAttribute = syncConfiguration.getOlatPropertyToLdapAttribute(LDAPConstants.LDAP_USER_IDENTIFYER); // LDAP_USER_IDENTIFYER == 'userID'
```

Line 595 in `LDAPSyncConfiguration.java `defines the function `getOlatPropertyToLdapAttribute()`:
```
public String getOlatPropertyToLdapAttribute(String olatProperty) {
```

It looks for `olatProperty` in the `userAttrMapper` hash, which comes from `Map<String, String> userAttrMapper = getRequestAttributes();`.

Line 440 in `LDAPSyncConfiguration.java` defines `getRequestAttributes()` function, which returns `requestAttributes` hash:
```
public Map<String, String> getRequestAttributes() {
```

The hash `requestAttributes` is set in `setRequestAttributes()` function defined on line 444 in `LDAPSyncConfiguration.java`:
```
public void setRequestAttributes(Map<String, String> mapping) {
  requestAttributes = new HashMap<>();
  for (Map.Entry<String, String>  entry : mapping.entrySet()) {
    requestAttributes.put(entry.getKey().trim(), entry.getValue().trim());
  }	
}
```

But using `grep` on whole `src` folder and subfolders, I cannot find any call of this function `setRequestAttributes()`, I see only onle line, this line with definition:
```
$ grep -RFi setRequestAttributes
main/java/org/olat/ldap/LDAPSyncConfiguration.java:     public void setRequestAttributes(Map<String, String> mapping) {
```

As I have written, I am no (java) developer so maybe I miss any java automation, which runs this function automagically? Or is really any code missing to set this mapping?

Thank you very much for any answer on this our problem.

Regards,

Robert Wolf.

**Comment by gnaegi** [comment]
Hi Robert
Sorry for the late reply, we are very busy at the moment in clients projekts. The short answer: yes of course, we have man working LDPA installations. I will look into your problems later today. 
Cheers
Florian

**Comment by wolfaba** [comment]
@gnaegi Great, thank you very much. :+1:

**Comment by lainsr** [comment]
Hi Robert

You map the same attribute to email:

ldap.attributename.useridentifyer=mail
ldap.attributename.email=mail

And OpenOlat doesn't like that. We don't recommend to use the email as user identifier. It can change or in enterprises, the email can be reused by other users.

Regards
Stéphane

**Comment by wolfaba** [comment]
Hello @lainsr ,
thank you for your hint.

> You map the same attribute to email:
> 
> ldap.attributename.useridentifyer=mail
> ldap.attributename.email=mail

In the `olat.properties` file there is example LDAP configuration and there is `nickName` attribute mapped to `useridentifyer` too:
```
ldap.attributename.useridentifyer=sAMAccountName
ldap.attributename.nickName=${ldap.attributename.useridentifyer}
```

> And OpenOlat doesn't like that. We don't recommend to use the email as user identifier. It can change or in enterprises, the email can be reused by other users.

But OK, I have changed the `useridentifyer` to `objectGUID`, which is the unique and persistent for each user:
```
ldap.attributename.useridentifyer=objectGUID
ldap.attributename.email=mail
ldap.attributename.nickName=mail
ldap.login.attribute=mail
```

And now everything works good. 

So the problem (NPE) arise only if the `email` and `useridentifyer` use the same LDAP attribute. Other attributes (`firstName`, `lastName`, `nickName`) may use the same LDAP attribute as `useridentifyer`, only `email` attribute may not, otherwise olat crashes with NPE.

It's clear now.

I am going to play with LDAP now.

Thank you for your explanation and support.

Regards,

Robert Wolf.
