### ISSUE TITLE
Date-select widget lacks sanity check (in execution settings)

### ISSUE THREAD

**Issue by Aratch** [OpenOLAT/OpenOLAT#92]
**OLAT Version**: 17.0.2

**Description**: My current job requires me to tediously duplicate courses and copy & paste settings and infos between existing courses and newly planned courses. This includes manually adjusting each duplicated course's execution time/timeframe (DE: _Durchführungszeitraum_). 

This frequently leads to typos and other small errors such as the one caught in the screenshot below: When entering an otherwise nonsensical date, the user is not given feedback that they might have put in an impossible date.

![image](https://user-images.githubusercontent.com/13820340/190444191-1c1725ea-4a31-47a1-b483-6ccf38633aa8.png)

![image](https://user-images.githubusercontent.com/13820340/190446177-d170c627-e06d-432c-b7ff-ac5f397bc9f6.png)

**Steps to Reproduce**:

1. Create new course or open existing one
2. Open course settings and switch to execution tab (DE: _Durchführung_)
3. Enter any ol' nonsense date and save the changed settings.
4. Optional: Confirm by looking at a list of courses with the start and end dates shown that the newly input date setting has been accepted. To be sure, the date entered (such as 22 A.D.) is parsed as such and influences, for instance, the sorting order.

**Suggestion**: Add some kind of sanity check to the date widget so it least triggers a warning.

**Comment by Aratch** [comment]
> This is a perfectly valid use case: a course that is held at a specific date. It starts in the morning and ends in the evening (a one day course

This is perfectly fine and that's how we're using the execution time as well. That's **not** what I was referring to, though.

> Regarding "nonsense date": can you provide an example of a date that does not make sense?

I'm pretty sure a course starting on the 15th of December 22, i.e. 22 A.D (22 _nach Christus_) and ending 2000 years later is not within the set of reasonable/possible use cases (see screenshots of the initial post; one shows two dates set to the year '0022' while the second shows that the year '0022' is not parsed as a shorthand for '2022').

**Comment by gnaegi** [comment]
@Aratch  it has been fixed here: https://jira.openolat.org/browse/OO-6487

**Comment by Aratch** [comment]
@gnaegi Beautiful, thank you!
