### ISSUE TITLE
Should use sha256 for BigBlueButton checksum

### ISSUE THREAD

**Issue by GhaziTriki** [OpenOLAT/OpenOLAT#93]
Hello,

You should think about using sha256 and other algos

https://github.com/OpenOLAT/OpenOLAT/blob/258561c4ee32b2259c84975129bd098b123a8643/src/main/java/org/olat/modules/bigbluebutton/manager/BigBlueButtonUriBuilder.java#L163

after this release https://github.com/bigbluebutton/bigbluebutton/releases/tag/v2.5.7

**Comment by lainsr** [comment]
Hi,


I Opened an issue for this. The changes will come with the OpenOlat release 18.2.0

https://jira.openolat.org/browse/OO-7388

Thank you for the report.
