### ISSUE TITLE
Cloud login conf is not persisted on db

### ISSUE THREAD

**Issue by pavriet-boxtal** [OpenOLAT/OpenOLAT#98]
Hello,

I am currently installing OpenOlat v18.0.6 on my company environment. We want to test if it can suit our need.

We only run apps on AWS ECS, so we only do docker. I adapted your installation guide (https://docs.openolat.org/manual_admin/installation/installGuide/) into a Dockerfile. It starts fine, and is connected to a postgre db (also on AWS).

We would like to use google login, because the company is used to this login method on other internal tools that we have. So I set it up on the openolat side (with the default admin account). It works fine, I can create an account with my professional google account, give me admin role, set profile pic, all ok.

I make some changes to my docker image, so I have to reboot the ECS service. Openolat restarts, but I can no longer login with google.

logging with the admin account, I see the conf has disappeared. My account still exists, but the pp is not there anymore.

So I guess not everything is stored on db, some is stored on disk. Can you tell me what is stored on disk, and most importantly, all the paths that have persistent data ?

Best regards,
Paul

**Comment by gnaegi** [comment]
Have a look at the config file:
https://docs.openolat.org/manual_admin/installation/installGuide/#openolat-configuration

There you have the parameters
```
log.dir=/home/openolat/logs
userdata.dir=/home/openolat/olatdata
```

We have not experience operating OpenOlat in an AWS setup, so we can't help any further.

**Comment by pavriet-boxtal** [comment]
Thats perfect, thank you.

The problem is more with docker than AWS.
