### ISSUE TITLE
Remove/Replace dep net.alchim31.maven / compressjs

### ISSUE THREAD

**Issue by Mando-C137** [OpenOLAT/OpenOLAT#99]
Das Minifyen der _.js-Dateien_ mittels [net.alchim31.maven](https://github.com/davidB/yuicompressor-maven-plugin)  akzeptiert kein ES6 und die dependency wird auch seit Jahren nicht mehr gepflegt (siehe [hier](https://github.com/davidB/yuicompressor-maven-plugin/issues/99)). 

Beispiel

` someArray.filter( val => val.includes("/"));
`

**Comment by lainsr** [comment]
Hi

We plan to replace it for OpenOlat 19.0. You can follow the issue here: https://track.frentix.com/issue/OO-7609
